name: Build APK

   on:
     push:
       branches: [ master ]  # 确保分支名与原仓库一致（可能是 master）

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up JDK
           uses: actions/setup-java@v3
           with:
             distribution: 'zulu'
             java-version: 11

         - name: Setup Android SDK
           uses: android-actions/setup-android@v2

         - name: Grant Gradle Permission
           run: chmod +x gradlew  # 确保可执行权限

         - name: Build Debug APK
           run: ./gradlew assembleDebug

         - name: Upload APK
           uses: actions/upload-artifact@v3
           with:
             name: app-debug
             path: app/build/outputs/apk/debug/app-debug.apk
